// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsHb3Z5NYWLOoZ3ETJk6XZIvsC7UEzu8M',
    appId: '1:94069755178:web:bf18f5cf8dfd2d672aa253',
    messagingSenderId: '94069755178',
    projectId: 'notes-app-50953',
    authDomain: 'notes-app-50953.firebaseapp.com',
    storageBucket: 'notes-app-50953.firebasestorage.app',
    measurementId: 'G-46JW0BEMR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNMxPfVEq6ZRKZFKYJljUDnt5Q2Ifg0M',
    appId: '1:94069755178:android:5c12888ab3a660602aa253',
    messagingSenderId: '94069755178',
    projectId: 'notes-app-50953',
    storageBucket: 'notes-app-50953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5igCrxTuya6_wjY-1xgsRAoFeKlfcvxw',
    appId: '1:94069755178:ios:7089a46393d4791c2aa253',
    messagingSenderId: '94069755178',
    projectId: 'notes-app-50953',
    storageBucket: 'notes-app-50953.firebasestorage.app',
    iosBundleId: 'com.example.noteAppAdam',
  );
}
